// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/networkee/Dark.tsx": () => import("../components/mockups/networkee/Dark.tsx"),
  "./components/mockups/networkee/Mobile.tsx": () => import("../components/mockups/networkee/Mobile.tsx"),
  "./components/mockups/networkee/Modern.tsx": () => import("../components/mockups/networkee/Modern.tsx")
};
